### ISSUE TITLE
[Feature]: qdrant as a vector store

### ISSUE THREAD

**Issue by regstuff** [zilliztech/GPTCache#132]
### Is your feature request related to a problem? Please describe.

Hi. Glad someone finally made this. Been on my mind for a long time.
Any chance of supporting qdrant as a vector store? Qdrant also allows filtering by metadata which can be helpful if you only want to retrieve cache from within a certain date range for example. Qdrant can also store the llm response as metadata which eliminates the sqlite requirement. The new qdrant local mode means you dont have to setup a server via docker. Just install from pip and you are ready to go.

**Comment by SimFG** [comment]
qdrant is on the list, please stay tuned.

**Comment by xiaofan-luan** [comment]
we actually has a pr for this.
If you want to implement the local mode version on yourself that would be highly welcomed

**Comment by dagthomas** [comment]
Any update on this?

**Comment by xiaofan-luan** [comment]
anyone interesting could take on the pr and work on this

**Comment by parthvnp** [comment]
Happy to start working on this!

**Comment by xiaofan-luan** [comment]
> Happy to start working on this!

Please take it and open an issue~ Anyone would like to work on any vector store is warmly welcomed~

**Comment by Torhamilton** [comment]
@parthvnp any update on qdrant?

**Comment by parthvnp** [comment]
@Torhamilton It will be ready by this Saturday!

**Comment by Torhamilton** [comment]
@parthvnp looking forward to your pr

**Comment by DumoeDss** [comment]
@parthvnp Hey~ how about the project update?

**Comment by parthvnp** [comment]
@DumoeDss @Torhamilton Sorry for the delay. I have created a [PR](https://github.com/zilliztech/GPTCache/pull/453)

**Comment by SimFG** [comment]
@parthvnp Thanks your contribution!!!
The next GPTCache version will support the qdrant vector database.
@DumoeDss @Torhamilton @dagthomas
