### ISSUE TITLE
[Query] : Not an issue, but a query - how to cache existing data and query offline

### ISSUE THREAD

**Issue by Mahabali** [zilliztech/GPTCache#150]
Pardon my ignorance. I am looking to build a offline cache with existing data and query offline. Can you let me know how to do it.

Can i save and search using **get_data_manager** from [documentation link](https://gptcache.readthedocs.io/en/latest/references/manager.html)

**Comment by SimFG** [comment]
You can try doing this:
```
question = "q1"
answer = "a1"
cache.data_manager.save(question, answer, cache.embedding_func(question))
```
Later we will provide the `import` interface to insert data in batches faster.

**Comment by SimFG** [comment]
If the above answer is the answer you want, please help close the issue, thank you. 🤗
@Mahabali

**Comment by SimFG** [comment]
@Mahabali 
we will support to import data set, like:
```
cache.import_data(questions=questions, answers=answers)
```
pr: #182
