### ISSUE TITLE
[Feature]: Support Image embedding and cache image as key.

### ISSUE THREAD

**Issue by xiaofan-luan** [zilliztech/GPTCache#156]
### Is your feature request related to a problem? Please describe.

For models like CLIP, and BLIP, we need to cache image as key

**Comment by Pouyanpi** [comment]
Hi @xiaofan-luan 

I would like to take over and work on this feature. For the time being I will only focus on the `embedding` module. I think ViT from transformers works the best. Below is a task list. Feel free to modify it.


- [x] Investigate and choose an appropriate image embedding model (e.g. ViT, ResNet, etc.)
- [ ] Implement an Image Embedding object inheriting from `BaseEmbedding`
- [ ] add tests for the image encoder 
- [ ] image preprocessing (e.g., `AutoImageProcessor` from transformers) or user defined.
- [ ] resolve the design conflict with the `hugginface.py`

"to cache image as key" is not clear for me.

p.s. with the current version, having hugging face tied to only text encoders is problematic because Vision and text in transformers have different interfaces.  Do you have any specific design pattern in mind to maybe extend the `huggingface.py`? any suggestion per the module and class name?

**Comment by xiaofan-luan** [comment]
> Hi @xiaofan-luan
> 
> I would like to take over and work on this feature. For the time being I will only focus on the `embedding` module. I think ViT from transformers works the best. Below is a task list. Feel free to modify it.
> 
> * [x]  Investigate and choose an appropriate image embedding model (e.g. ViT, ResNet, etc.)
> * [ ]  Implement an Image Embedding object inheriting from `BaseEmbedding`
> * [ ]  add tests for the image encoder
> * [ ]  image preprocessing (e.g., `AutoImageProcessor` from transformers) or user defined.
> * [ ]  resolve the design conflict with the `hugginface.py`
> 
> "to cache image as key" is not clear for me.
> 
> p.s. with the current version, having hugging face tied to only text encoders is problematic because Vision and text in transformers have different interfaces. Do you have any specific design pattern in mind to maybe extend the `huggingface.py`? any suggestion per the module and class name?

Resnet and Clip is what I'm thinking about~

But we still need to think of the output , or our task?
BLIP2 is a demo, with a image + question, the model generated answer based on image and question 
https://replicate.com/andreasjansson/blip-2

**Comment by xiaofan-luan** [comment]
Another interesting use case is Image2prompt, which is the newly released feature in Midjourny.

**Comment by Pouyanpi** [comment]
@xiaofan-luan thanks for your comments. Below is an example of how image embedding could be.

The contribution workflow and guidelines are not clear for me that's why I'm doing it here:

```python

import numpy as np

from gptcache.utils import import_huggingface, import_torch, import_torchvision
from gptcache.embedding.base import BaseEmbedding

import_torch()
import_huggingface()
import_torchvision()

import torch # pylint: disable=C0413
from torchvision import transforms

from transformers import AutoImageProcessor
from transformers import ViTModel


class ImageEmbedding(BaseEmbedding):
    """Generate sentence embedding for given text using pretrained models from Huggingface transformers.

    :param model: model name, defaults to 'google/vit-base-patch16-384'.
    :type model: str
    :param image_processor: the 

    Example:
        .. code-block:: python
            import io
            from PIL import Image
            from gptcache.embedding import ImageEmbedding

            def prepare_image(image_data: str = None):
                if not image_data:
                    image_data = io.BytesIO()
                    Image.new('RGB', (244, 244), color=(255, 0, 0)).save(image_data, format='JPEG')
                    image_data.seek(0)
                image = Image.open(image_data)
                return image

            image = prepare_image()
            encoder = ImageEmbeddings(model="google/vit-base-patch16-384")
            embed = encoder.to_embeddings(image)
    """

    def __init__(self, 
                    model: str = "google/vit-base-patch16-384",
                    image_processor: callable = None, # NOTE: Design CHOICE: image_preprocessor is more aligned with the transformers and the literature, but in cachgpt 'pre_proc' is mostly used. 
                    ):
        
        

        if image_processor is None:
            image_processor = AutoImageProcessor.from_pretrained(model)
        self.image_processor = image_processor

        vit_model = ViTModel.from_pretrained(model)
        self.vit_model = vit_model.eval()
        
        config = self.vit_model.config
        self.__dimension = config.hidden_size

    def to_embeddings(self, data, **__):
        """Generate embedding given text input

        :param data: text in string.
        :type data: str

        :return: a text embedding in shape of (dim,).
        """
        inputs = self.image_processor(data, return_tensors="pt")

        with torch.no_grad():
            outputs = self.vit_model(**inputs)

        last_hidden_states = outputs.last_hidden_state
        features = last_hidden_states[:, 0, :]
        features = features.squeeze()

        return features.detach().numpy()


    @property
    def dimension(self):
        """Embedding dimension.

        :return: embedding dimension
        """
        return self.__dimension   

```

- [ ] the namings SHOULD change.
- [ ] using builder pattern would be useful

**Comment by jaelgu** [comment]
@Pouyanpi Your code looks good! Just need some small changes. Check my pr of timm embedding here: #249. Would you like to submit a pull request so we can have code review there?

**Comment by Pouyanpi** [comment]
@jaelgu Sure, your PR is what I've been looking for. Thanks
 I will open a PR soon.

**Comment by jaelgu** [comment]
Close as completed. More contributions are welcome! To contribute image embedding modules, please refer to #249 and #270 as examples.
