### ISSUE TITLE
[Feature]: Support to store images in cache storage.

### ISSUE THREAD

**Issue by xiaofan-luan** [zilliztech/GPTCache#157]
### Is your feature request related to a problem? Please describe.

For models working on image generation, we can store the result image in cache storage rather than just text.

TODO: support minio cache storage backend and local disk storage backend

**Comment by fzliu** [comment]
@xiaofan-luan I'll take a stab at this later this week or over this weekend if nobody else beats me to it

**Comment by jiaoew1991** [comment]
> @xiaofan-luan I'll take a stab at this later this week or over this weekend if nobody else beats me to it

I suggest using opendal as the access layer for storage. It provides a unified interface to access file systems, memory, S3, etc. Although it is written in Rust, it has bindings for various languages especially Python.

https://github.com/apache/incubator-opendal/blob/main/bindings/python/README.md

**Comment by SimFG** [comment]
The latest version of GPTCache have implemented it, pr: #213. So i will close the issue. @jiaoew1991  But we didn't use the `opendal` as the access layer for storage. If we need to access more object storage in the future, we will consider using it.
