### ISSUE TITLE
[Feature]: JavaScript/TypeScript Port

### ISSUE THREAD

**Issue by andenacitelli** [zilliztech/GPTCache#175]
Python is obviously the ecosystem to be in for ML at the moment, but offering an easy interface for JavaScript/TypeScript (which is extremely common to use for both frontend and backend) could help increase library adoption.

I'd be curious to hear thoughts on the best approach for this, or if it's even a good idea, from those more knowledgeable. Would basically embedding this library be the best way, so that the code generally only needs written once? Or would a full port in JS probably be worth it, as to my understanding this isn't actually doing anything data-intensive or ML-intensive like creating the embeddings or the database system, and it would mostly just be syntactical changes instead of creating anything new?

**Comment by SimFG** [comment]
Good idea, we will try to support it. please stay tuned. Of course, we also welcome contributions.

**Comment by aacitelli** [comment]
I'm happy to contribute and get started on it, would just need a bit of guidance on high-level architecture. Would a full rewrite make sense, or would basically embedding this library and calling via node's [child_process](https://nodejs.org/api/child_process.html) be better?

**Comment by shanghaikid** [comment]
> I'm not an expert on both nodejs and python but what about another wrapper?
> 
> @SimFG @aacitelli @shanghaikid (https://www.npmjs.com/package/node-calls-python)

From performance perspective, calling python from nodejs is not a good option,  personally I agree with @SimFG, a server is a better option.

**Comment by xiaofan-luan** [comment]
> 

does it really matters for a 100ms responses?

**Comment by xiaofan-luan** [comment]
> > 
> 
> does it really matters for a 100ms responses?

Personally i want to keep GPTCache light before we moved to C/S style

**Comment by SimFG** [comment]
My idea is to wrap it into a very simple docker service, so that other languages can experience GPTCache through the interface.

**Comment by xiaofan-luan** [comment]
works for me. just a very simple python with grpc or restful?

**Comment by SimFG** [comment]
> works for me. just a very simple python with grpc or restful?

yes, provide two restful interfaces, the names are `search` and `save`, or like redis, called `get` and `set`

**Comment by aacitelli** [comment]
> does it really matters for a 100ms responses?

Agree that performance shouldn't be a primary concern, more just a bonus. Seems to me like, seeing as a network round-trip is core to this library, optimizing for performance isn't really worth it, especially considering the library itself isn't doing the heavy computation.

**Comment by shanghaikid** [comment]
> > does it really matters for a 100ms responses?
> 
> Agree that performance shouldn't be a primary concern, more just a bonus. Seems to me like, seeing as a network round-trip is core to this library, optimizing for performance isn't really worth it, especially considering the library itself isn't doing the heavy computation.

I agree with you, anyway, calling python from node is not a good practice and its scope will be limited within backend and it's hard to debug.  Personally I prefer a typescript rewrite, but some features are not portable for node, because they are not available in node, for example faiss.

**Comment by aacitelli** [comment]
I'd ultimately prefer a full TypeScript rewrite as well. Probably better for the long/term future and maturity of the project, and decoupling the two so they can make different decisions if necessary is probably a good idea.

**Comment by SimFG** [comment]
@andenacitelli We have implemented a simple version of the server (similar match), but currently requires a python environment to run. After installing gptcache, you can directly run the [`gptcache_server.py`](https://github.com/zilliztech/GPTCache/blob/main/gptcache_server/server.py) file. Further development we are in progress, such as packaging into binary and docker

**Comment by SimFG** [comment]
we have published the docker image, which means you can use GPTCache in any language, details: https://github.com/zilliztech/GPTCache/blob/main/docs/usage.md#use-gptcache-server
so i will close the issue

**Comment by Morriz** [comment]
>  I prefer a typescript rewrite, but some features are not portable for node, because they are not available in node, for example faiss.

That is not true nowadays:

```ts
  const embedding = new OpenAIEmbeddings()
  const store = await FaissStore.loadFromPython('vectorstore', embedding)
  retriever = store.asRetriever(5)
```

**Comment by Morriz** [comment]
> we have published the docker image, which means you can use GPTCache in any language, details: https://github.com/zilliztech/GPTCache/blob/main/docs/usage.md#use-gptcache-server
> so i will close the issue

that is like saying everybody should start using microservices...
