### ISSUE TITLE
please give some usage scenarios for GPTCache

### ISSUE THREAD

**Issue by ZZBoom** [zilliztech/GPTCache#192]
Hi

I am very confused with scenarios like AI chat, NPCs in the game which seems not really suitable for GPTCache, as these requests' contents are almost diifferent.

Although similarity evaluation can estimate some similarity requests and then making responses from GPTCahe, the responses' performance seems make a little worse than from LLM.

So can you give some typical scenarios that can be applied with GPTCache?  What I mean is what characteristics do GPTCache scenarios conform to?

thanks!

**Comment by xiaofan-luan** [comment]
> 

Hi ZZBoom,

We have identified a few use cases:

1. Our [https://osschat.io/](https://osschat.io/) project involves users asking questions for the open-source community, such as "What is PyTorch?"
2. If you are building an app for paper Q&A, GPTCache can cache the paper and the questions. When similar questions arise, it can directly use the cached results.
3. If you are using OpenAI Whisper, you could cache the audio and its transcript as a peer, no don't need to translate again.

Locality is all you need for using semantic cache. Not all scenarios will fit the semantic cache, but there will be some.

Furthermore, the local model should be much faster than ChatGPT, as shown in our benchmark [https://zilliz.com/blog/Yet-another-cache-but-for-ChatGPT](https://zilliz.com/blog/Yet-another-cache-but-for-ChatGPT).

**Comment by ZZBoom** [comment]
Thanks @xiaofan-luan for your quick reply! May I take it that the scenarios with limited questions are more suitably applied with GPTCache?

**Comment by SimFG** [comment]
For a specific field and user group or at a given time, certain problems may have a particular range, which is also very suitable for GPTCache.

**Comment by xiaofan-luan** [comment]
> Thanks @xiaofan-luan for your quick reply! May I take it that the scenarios with limited questions are more suitably applied with GPTCache?

Yes, for a cache to work it has to be focusing on certain domain, not like a real chatbot
