### ISSUE TITLE
[Feature]: Support DynamoDB

### ISSUE THREAD

**Issue by alvations** [zilliztech/GPTCache#200]
### Is your feature request related to a problem? Please describe.

It's like nosql but just comes with all the AWS support https://aws.amazon.com/dynamodb/

### Describe the solution you'd like.

Possibly hook up the dynamodb through https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html then populate or fetch from it.

### Describe an alternate solution.

Maybe mongo atlas? https://www.mongodb.com/cloud/atlas/register 

### Anything else? (Additional Context)

Thanks for the work on the cache implementations! 

Naming suggestions: Perhaps, you can disconnect the GPT once the hype is over and call it something else because I think this cache can be applied to many ML/NLP/CV applications beyond just GPT things.

**Comment by SimFG** [comment]
Thanks for your suggestion, we will try it.

**Comment by gauthamchandra** [comment]
@alvations, you can probably close this issue btw if you feel like the changes in #531 are adequate for your needs.

**Comment by SimFG** [comment]
i will close it! thanks a lot, @gauthamchandra
