### ISSUE TITLE
[Feature]: Think of adding concept of session 

### ISSUE THREAD

**Issue by xiaofan-luan** [zilliztech/GPTCache#201]
### Is your feature request related to a problem? Please describe.

There are couple of cases where we need the idea of session and context.

Let me quickly go through some examples:

<img width="902" alt="image" src="https://user-images.githubusercontent.com/83447078/231842592-af53e2a5-2947-4072-aefe-e51125db99ed.png">

Another use case is the langchain SQL demo, see (https://python.langchain.com/en/latest/modules/chains/examples/sqlite.html)
The chain did follow:
1. Based on the query, determine which tables to use.
2. Based on those tables, call the normal SQL database chain.
The chain request context so it won't hit the second time

**Comment by SimFG** [comment]
session: #294
context: #305 #316
