### ISSUE TITLE
[Bug]: error: update_cache_func() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by chenmingjia** [zilliztech/GPTCache#215]
### Current Behavior

![image](https://user-images.githubusercontent.com/12949392/232315670-9c6a03a2-30ae-43b5-bd2e-947f76b752b3.png)

I ran the demo of Github in colab, but encountered an error. The error message is as follows: WARNING: root: failed to save the data to cache, error: update_cache_func() takes 1 positional argument but 2 were given. How can I fix this?

### Expected Behavior

Successfully cached information

### Environment

```markdown
colab
```

**Comment by SimFG** [comment]
What version of GPTCache are you using

**Comment by chenmingjia** [comment]
I think I might have cloned the wrong branch,  everything runs smoothly now when I switch to the new branch

**Comment by SimFG** [comment]
@chenmingjia thanks your feedback. and i try the latest GPTCache version, and it's ok. If you have any question, please keep free to tell me.
