### ISSUE TITLE
[Feature]: Streaming support

### ISSUE THREAD

**Issue by gbertb** [zilliztech/GPTCache#245]

**Comment by SimFG** [comment]
At present, GPTCache already supports the streaming request of chat complete in openai, can you describe the problems encountered in detail?

**Comment by xiaofan-luan** [comment]
@SimFG 
is there a demo for streaming support?

**Comment by SimFG** [comment]
It is consistent with openai's api usage, like:
```python
from gptcache.adapter import openai

question = "calculate 1+1"
openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": question},
        ],
        stream=True,
    )
```

**Comment by SimFG** [comment]
@gbertb I hope the above response has adequately answered your question. If you have any further inquiries, please do not hesitate to provide feedback and ask. With that, I will now close this issue.
