### ISSUE TITLE
[Feature]: Support MongoDB Atlas for both scalar and vector data

### ISSUE THREAD

**Issue by Adam-Gibbs** [zilliztech/GPTCache#269]
### Is your feature request related to a problem? Please describe.

As noted in https://github.com/zilliztech/GPTCache/issues/200 It would be nice to have a NoSQL implementation, personally I prefer Mongo to DynamoDB due to the breath of operations you can perform on it compared to Dynamo.

### Describe the solution you'd like.

Hooking into their python driver [PyMongo](https://www.mongodb.com/docs/drivers/pymongo/) to store the scalar data in a standard NoSQL format. Mongo also offer a graph database option for storing and accessing the vector data [MongoDB as a Graph Database](https://www.mongodb.com/databases/mongodb-graph-database). I would like to have a simplified data storage solution only using one provider.

### Anything else? (Additional Context)

Also, this is brilliant, was a few weeks away from trying to create something similar for myself. But this is a great solution for my problems.

**Comment by SimFG** [comment]
@Adam-Gibbs Thanks your attention. Contributions are also welcome if possible.

**Comment by xiaofan-luan** [comment]
MongoDB is a good idea!

**Comment by SimFG** [comment]
The latest version has supported the mongo db as the cache store
