### ISSUE TITLE
[Feature]:Support the PaddleNLP Embedding

### ISSUE THREAD

**Issue by martinou** [zilliztech/GPTCache#281]
### Is your feature request related to a problem? Please describe.

支持PaddleNLP实现Embedding

### Describe the solution you'd like.

支持PaddleNLP实现Embedding

### Describe an alternate solution.

支持PaddleNLP实现Embedding

### Anything else? (Additional Context)

支持PaddleNLP实现Embedding

**Comment by jaelgu** [comment]
Contributions are also welcome!

**Comment by SimFG** [comment]
the latest version has supported link: #377
