### ISSUE TITLE
[Feature]: Support for mutually exclusive multiple contexts

### ISSUE THREAD

**Issue by Viswa4599** [zilliztech/GPTCache#291]
### Is your feature request related to a problem? Please describe.

I am currently working on something that has uses multiple GPT3.5 contexts. The sharing of cache between those contexts throws up some errors. Is there a way to set up data_manager in a way that can name dbs differently ?

**Comment by xiaofan-luan** [comment]
> ### Is your feature request related to a problem? Please describe.
> I am currently working on something that has uses multiple GPT3.5 contexts. The sharing of cache between those contexts throws up some errors. Is there a way to set up data_manager in a way that can name dbs differently ?
> 
> ### Describe the solution you'd like.
> _No response_
> 
> ### Describe an alternate solution.
> _No response_
> 
> ### Anything else? (Additional Context)
> _No response_

We are actually working on this.
Each of the request can has each own session IDs, so on search you can specify different sessions.
Another way to do is to init multiple cache object, something like that

def init_gptcache_map(cache_obj: gptcache.Cache):
    global i
    cache_path = f'{file_prefix}_{i}.txt'
    onnx = Onnx()
    cache_base = CacheBase('sqlite')
    vector_base = VectorBase('faiss', dimension=onnx.dimension)
    data_manager = get_data_manager(cache_base, vector_base, max_size=10, clean_size=2)
    cache_obj.init(
        pre_embedding_func=get_prompt,
        embedding_func=onnx.to_embeddings,
        data_manager=data_manager,
        similarity_evaluation=SearchDistanceEvaluation(),
    )
    i += 1

langchain.llm_cache = GPTCache(init_gptcache_map)

**Comment by Viswa4599** [comment]
Nice, I'll use this workaround for now.

**Comment by xiaofan-luan** [comment]
> Nice, I'll use this workaround for now.

~ I missed up, don't forget to have data_path=cache_path

**Comment by SimFG** [comment]
@Viswa4599 If the above answer solves your problem, please help close this issue. Thank you very much for your attention.
