### ISSUE TITLE
Listen as an OpenAI API?

### ISSUE THREAD

**Issue by JamesFlare1212** [zilliztech/GPTCache#319]
I checked the document, I am thinking is that possible to make the GPTCache listen as an OpenAI like API? So we can just connect it to other service via OpenAI API, such as ChatBox.

**Comment by xiaofan-luan** [comment]
> he GPTCache listen as an OpenAI like API? So we can just connect it to other service via OpenAI API, such as ChatBox.

Hi James,
Don't quite get your point. if you use OpenAI Adapter then the GPTCache is already OpenAI style API?

**Comment by SimFG** [comment]
it will be supported in the next version.
