### ISSUE TITLE
[Bug]: Session is module is not working as expect

### ISSUE THREAD

**Issue by moming133** [zilliztech/GPTCache#322]
### Current Behavior

when i run the example Sqlite + Faiss + ONNX, i get the following error. 
And i try to add __enter__ and exit function in the sql_storage.py, but it's not working .

    def __enter__(self):
        print("debug: enter function test")
        return self

    def __exit__(self):  # 
        self.drop()

    def drop(self):
        self._data_manager.delete_session(self.name)
        print("debug:drop sql connnect")

------------------------
return SSDataManager(cache_base, vector_base, object_base, max_size, clean_size, eviction)
  File "C:\ProgramData\Anaconda3\lib\site-packages\gptcache\manager\data_manager.py", line 209, in __init__
    self.eviction_base.put(self.s.get_ids(deleted=False))
  File "C:\ProgramData\Anaconda3\lib\site-packages\gptcache\manager\scalar_data\sql_storage.py", line 229, in get_ids
    with self.Session() as session:
AttributeError: __enter__

### Environment

```markdown
python : 3.8.3
```

**Comment by xiaofan-luan** [comment]
/assign @shiyu22 
could you take a look at the bug

**Comment by moming133** [comment]
Thanks , and this is the script:
------------------------
import time


def response_text(openai_resp):
    return openai_resp['choices'][0]['message']['content']

from gptcache import cache
from gptcache.adapter import openai
from gptcache.embedding import Onnx
from gptcache.manager import CacheBase, VectorBase, get_data_manager
from gptcache.similarity_evaluation.distance import SearchDistanceEvaluation

print("Cache loading.....")

onnx = Onnx()
data_manager = get_data_manager(CacheBase("sqlite"), VectorBase("faiss", dimension=onnx.dimension))
cache.init(
    embedding_func=onnx.to_embeddings,
    data_manager=data_manager,
    similarity_evaluation=SearchDistanceEvaluation(),
    )
cache.set_openai_key()

questions = [
    "what's github",
    "can you explain what GitHub is",
    "can you tell me more about GitHub"
    "what is the purpose of GitHub"
]

for question in questions:
    start_time = time.time()
    response = openai.ChatCompletion.create(
        model='gpt-3.5-turbo',
        messages=[
            {
                'role': 'user',
                'content': question
            }
        ],
    )
    print(f'Question: {question}')
    print("Time consuming: {:.2f}s".format(time.time() - start_time))
    print(f'Answer: {response_text(response)}\n')

**Comment by SimFG** [comment]
@moming133 i use the latest GPTCache version(0.1.21), there is no error. can you tell me the version you used.

**Comment by SimFG** [comment]
@moming133 have your problem been solved? if there is no problem, i will close the issue
