### ISSUE TITLE
[Bug]: Customize Cache

### ISSUE THREAD

**Issue by susoooon** [zilliztech/GPTCache#324]
### Current Behavior

want to customize the component, in order to add more static methods，such as openai base_url。But I got an error whether i remove cache.__init__ or not 

gptcache.utils.error.NotInitError: The cache should be inited before using

![e723a566fd615b807766efafcde3969](https://user-images.githubusercontent.com/40882819/236596272-5835d054-db59-48c5-8f2f-53cd8fc7c1ab.png)

### Environment

```markdown
linux
latest packages
```

**Comment by SimFG** [comment]
can you give me a simple example? let me try to test it

**Comment by SimFG** [comment]
@susoooon hello, is there your problem? If you encounter any problem about gptcache usage, please give me a new issue. And i will close it.
