### ISSUE TITLE
[Bug]: 'sentence-transformers/paraphrase-albert-small-v2' is NOT a correct model identifier listed on Huggingface

### ISSUE THREAD

**Issue by tuoittm** [zilliztech/GPTCache#328]
### Current Behavior

I installed the latest version of GPTCache (0.1.22) and run:
```
from gptcache.embedding import Onnx
Onnx()
```
then I see the error message below:
```
OSError: Can't load config for 'sentence-transformers/paraphrase-albert-small-v2'. Make sure that:

- 'sentence-transformers/paraphrase-albert-small-v2' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'sentence-transformers/paraphrase-albert-small-v2' is the correct path to a directory containing a config.json file
```
I checked on Huggingface, and that model is no longer available.
Thank you.

**Comment by SimFG** [comment]
@tuoittm thanks your feedback, i will checkout it.

**Comment by wxywb** [comment]
https://twitter.com/huggingface/status/1655760648926642178
We used sentence-transformers(hosted on Huggingface) as our embedding backbone, it seems they currently meet a bug. It will be okay when they fix their bug.

**Comment by tuoittm** [comment]
> https://twitter.com/huggingface/status/1655760648926642178 We used sentence-transformers(hosted on Huggingface) as our embedding backbone, it seems they currently meet a bug. It will be okay when they fix their bug.

Thank you.

**Comment by jaelgu** [comment]
Huggingface has fixed its bug: https://twitter.com/huggingface/status/1656004153162756100?cxt=HHwWiMCz_ZvAp_stAAAA
