### ISSUE TITLE
[Feature]: PostgreSQL pgvector as vector store

### ISSUE THREAD

**Issue by ProGM** [zilliztech/GPTCache#332]
### Is your feature request related to a problem? Please describe.

[pgvector](https://github.com/pgvector/pgvector) is an extension for PostgreSQL that allows vector similarity search.
Any chance of supporting it as a vector store?

Personally, I see it very interesting since it may allow to run GPTCache with a single DB Engine (Postgres both as a cache store and a Vector Store) and it was lately supported on [AWS RDS](https://aws.amazon.com/about-aws/whats-new/2023/05/amazon-rds-postgresql-pgvector-ml-model-integration/) and other [hosted solutions](https://github.com/pgvector/pgvector/issues/54).

**Comment by SimFG** [comment]
Thanks your feedback, it will be added our plan and we warmly welcome contributions. 🤝
