### ISSUE TITLE
[Feature]: Support Weaviate as an option for a vector store

### ISSUE THREAD

**Issue by hsm207** [zilliztech/GPTCache#340]
### Is your feature request related to a problem? Please describe.

I want to use weaviate to find the K most similar requests from the input request's extracted embedding

### Describe the solution you'd like.

Be able to do this:

`data_manager = get_data_manager(CacheBase("weaviate"), VectorBase("weaviate", dimension=128))`

or at least:

`data_manager = get_data_manager(CacheBase("other db"), VectorBase("weaviate", dimension=128))`

### Describe an alternate solution.

None 😀

**Comment by xiaofan-luan** [comment]
feel free to contribute one, shouldn't be too hard

**Comment by pranaychandekar** [comment]
@hsm207 added the support for weaviate as a part of pr: #493 . Now you will be able to at least do this 😉:

`data_manager = get_data_manager(CacheBase("other db"), VectorBase("weaviate"))`

**Comment by SimFG** [comment]
the latest version has support the Weaviate vector store
