### ISSUE TITLE
[Feature]: higher onnx similarity evaluation token limit

### ISSUE THREAD

**Issue by elBarkey** [zilliztech/GPTCache#360]
### Is your feature request related to a problem? Please describe.

currently the implemented onnx similarity evalution using "GPTCache/albert-duplicate-onnx" is limited to 512 token, is it possible to get higher than 512?

### Describe the solution you'd like.

using langchain conversational chat agent prompt producing aroute 600s to thousands of tokens, it will be easier to get the cache hit without reducing the prompt's token size using onnx similiarity evaluation

**Comment by wxywb** [comment]
Currently, we prefer light model to evaluate sentence pair similarity(for lower latency and the[ training dataset](https://quoradata.quora.com/First-Quora-Dataset-Release-Question-Pairs) also consists of short sentences), for long sentences, you can try other similarity evaluations,  I have personally make a benchmark to test them, you can have a check(https://github.com/wxywb/gptcache_osschat_benchmark) .

**Comment by SimFG** [comment]
@wxywb Surely, if you have a good idea, we warmly welcome contributions as well. 🤝

**Comment by SimFG** [comment]
@elBarkey now you can use the latest version to get more accurate cache answer by the [sbert_crossencoder](https://gptcache.readthedocs.io/en/latest/references/similarity_evaluation.html#module-gptcache.similarity_evaluation.sbert_crossencoder) or [cohere_rerank](https://gptcache.readthedocs.io/en/latest/references/similarity_evaluation.html#module-gptcache.similarity_evaluation.cohere_rerank) similarity evaluation
