### ISSUE TITLE
[Bug]: Multiple messages not answering last message

### ISSUE THREAD

**Issue by deerleo** [zilliztech/GPTCache#373]
### Current Behavior

Using openai's api, 
when I passed multiple messages to the openai, it randomly returns one of the questions' answer .

### Expected Behavior

Only return answer of last question.

**Comment by SimFG** [comment]
@Suley Thanks your issue, can you give me your code snippet?

**Comment by Suley** [comment]
I used flask to provide api(because unable to figure out how to use gptserver)


```
from flask import Flask
app = Flask(__name__)
from flask import request, jsonify

import time

from gptcache import cache, Config
from gptcache.manager import manager_factory
from gptcache.embedding import Onnx
from gptcache.processor.post import temperature_softmax
from gptcache.similarity_evaluation.distance import SearchDistanceEvaluation
from gptcache.adapter import openai

cache.set_openai_key()

onnx = Onnx()
data_manager = manager_factory("sqlite,faiss", vector_params={"dimension": onnx.dimension})

cache.init(
    embedding_func=onnx.to_embeddings,
    data_manager=data_manager,
    similarity_evaluation=SearchDistanceEvaluation(),
    post_process_messages_func=temperature_softmax
    )
# cache.config = Config(similarity_threshold=0.9)

@app.route('/')
def hello_world():
    return 'Hello World!'

@app.route('/chatgpt', methods = ["POST"])
def chatgpt():
    start = time.time()
    data = request.get_json()
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        temperature = 1.0,  # Change temperature here
        messages=data
    )
    return response

if __name__ == '__main__':
    app.run(host='0.0.0.0')
```

here is the requested post data i sent to the wrapped openai api: 

```
[
    {
        "role": "user",
        "content": "怎么制作一杯咖啡" // how to make a cup of coffee
    },
    {
        "role": "user",
        "content": "今天天气怎么样" // how's the weather today.
    }
]
```

When I sent this messages multiple times, it randomly returns answers of the weather and the coffee making questions. not responding stable

**Comment by SimFG** [comment]
You need to change the embedding model, because the onnx embedding model only support the english, you can tru to use the huggingface embedding model, like:
```
from gptcache.embedding import Huggingface

huggingface = Huggingface(model='uer/albert-base-chinese-cluecorpussmall')

data_manager = manager_factory("sqlite,faiss", vector_params={"dimension": huggingface.dimension})

cache.init(
    embedding_func=huggingface.to_embeddings,
    data_manager=data_manager,
    similarity_evaluation=SearchDistanceEvaluation(),
    post_process_messages_func=temperature_softmax
    )

```

**Comment by Suley** [comment]
still not working after changed the embedding model from onnx to huggingface. 
Still replied to last question instead of current question.

**Comment by SimFG** [comment]
My test snippet:
```python
import time

from gptcache import cache
from gptcache.adapter import openai
from gptcache.embedding import Huggingface
from gptcache.manager import manager_factory
from gptcache.processor.post import temperature_softmax
from gptcache.processor.pre import all_content
from gptcache.similarity_evaluation.distance import SearchDistanceEvaluation

cache.set_openai_key()

huggingface = Huggingface(model="uer/albert-base-chinese-cluecorpussmall")
data_manager = manager_factory(
    "sqlite,faiss", data_dir="api_cache", vector_params={"dimension": huggingface.dimension}
)
cache.init(
    pre_embedding_func=all_content,
    embedding_func=huggingface.to_embeddings,
    data_manager=data_manager,
    similarity_evaluation=SearchDistanceEvaluation(),
    post_process_messages_func=temperature_softmax,
)

data = [{"role": "user", "content": "怎么制作一杯咖啡"}, {"role": "user", "content": "今天天气怎么样"}]

for _ in range(0, 2):
    start = time.time()
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo", temperature=1.0, messages=data
    )
    end = time.time()
    print(f"response: {response}")
    print(f"time delta: {end - start}")
```

test result:
![image](https://github.com/zilliztech/GPTCache/assets/21985684/66cc654c-9a7b-431b-b301-c644b76670bb)

**Comment by SimFG** [comment]
When i change the data param to `data = [{"role": "user", "content": "怎么制作一杯咖啡\n今天天气怎么样"}]`
result is:
![5HGsh7rh1t](https://github.com/zilliztech/GPTCache/assets/21985684/dd8ee9b7-e6a9-41f2-916c-5039ab81e6ac)

when i use the origin openai for the data `data = [{"role": "user", "content": "怎么制作一杯咖啡"}, {"role": "user", "content": "今天天气怎么样"}]`
```
import time

import openai

data = [{"role": "user", "content": "怎么制作一杯咖啡"}, {"role": "user", "content": "今天天气怎么样"}]
start = time.time()
response = openai.ChatCompletion.create(
    model="gpt-3.5-turbo", temperature=1.0, messages=data
)
end = time.time()
print(f"response: {response}")
print(f"time delta: {end - start}")
```
result:
![75Xojx9kXp](https://github.com/zilliztech/GPTCache/assets/21985684/9db0f34d-1c46-40ed-8f6f-ae429e05fb9b)
![vkvnzyGDSG](https://github.com/zilliztech/GPTCache/assets/21985684/f7c6bc7c-4375-45c1-8eb8-dc36e4f06dc3)

**Comment by Suley** [comment]
how about testing it multiple times? can you get stable response?

**Comment by SimFG** [comment]
![image](https://github.com/zilliztech/GPTCache/assets/21985684/6cf66a43-05e7-4944-9805-86a24cda7d93)

**Comment by Suley** [comment]
> ![image](https://user-images.githubusercontent.com/21985684/239904607-6cf66a43-05e7-4944-9805-86a24cda7d93.png)

I removed this for loop. using flask to expose an api to provide service.

@app.route('/chatgpt', methods = ["POST"])
def chatgpt():
    start = time.time()
    data = request.get_json()
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        temperature = 1.0,  # Change temperature here
        messages=data
    )
    return response

**Comment by SimFG** [comment]
you can try to add the `pre_embedding_func` func, because the default pre-processor only get the last message of the message array

```
cache.init(
    pre_embedding_func=all_content,
    embedding_func=huggingface.to_embeddings,
    data_manager=data_manager,
    similarity_evaluation=SearchDistanceEvaluation(),
    post_process_messages_func=temperature_softmax,
)
```

**Comment by SimFG** [comment]
@deerleo hi, has your problem been solved? If it has, i will close the issue

**Comment by deerleo** [comment]
> 

Still no luck.
problem exists.

Here is my code and test result.

```
import time

from gptcache import cache, Config
from gptcache.manager import manager_factory
from gptcache.embedding import Onnx
from gptcache.processor.post import temperature_softmax
from gptcache.similarity_evaluation.distance import SearchDistanceEvaluation
from gptcache.adapter import openai
from gptcache.processor.pre import all_content
from gptcache.embedding import Huggingface

huggingface = Huggingface(model='uer/albert-base-chinese-cluecorpussmall')

cache.set_openai_key()

onnx = Onnx()
data_manager = manager_factory("sqlite,faiss", vector_params={"dimension": huggingface.dimension})

cache.init(
    pre_embedding_func=all_content,
    embedding_func=huggingface.to_embeddings,
    data_manager=data_manager,
    similarity_evaluation=SearchDistanceEvaluation(),
    post_process_messages_func=temperature_softmax
#    embedding_func=onnx.to_embeddings,
#    data_manager=data_manager,
#    similarity_evaluation=SearchDistanceEvaluation(),
#    post_process_messages_func=temperature_softmax
    )
```
As you can see, the response still output history answer. (the question not in the current request)
![Uploading WechatIMG437.png…]()

**Comment by SimFG** [comment]
Hi, @deerleo As I said before, if the llm request is Chinese, you need to use the embedding model that supports Chinese; if it is English, you need to use the embedding model that supports English; if it is bilingual, you need to use the model that supports bilingual.

**Comment by deerleo** [comment]
> from gptcache.embedding import Huggingface
> 
> huggingface = Huggingface(model='uer/albert-base-chinese-cluecorpussmall')
> 
> data_manager = manager_factory("sqlite,faiss", vector_params={"dimension": huggingface.dimension})
> 
> cache.init(
>     embedding_func=huggingface.to_embeddings,
>     data_manager=data_manager,
>     similarity_evaluation=SearchDistanceEvaluation(),
>     post_process_messages_func=temperature_softmax
>     )

Hi, I already changed from onnx to hugging face model as you told before:

```
from gptcache.embedding import Huggingface

huggingface = Huggingface(model='uer/albert-base-chinese-cluecorpussmall')

data_manager = manager_factory("sqlite,faiss", vector_params={"dimension": huggingface.dimension})

cache.init(
    embedding_func=huggingface.to_embeddings,
    data_manager=data_manager,
    similarity_evaluation=SearchDistanceEvaluation(),
    post_process_messages_func=temperature_softmax
    )

```

**Comment by deerleo** [comment]
> 

Used english to test it. It works. So it's the bilingual embedding model issue.

**Comment by SimFG** [comment]
yes, reference: #374
