### ISSUE TITLE
[Enhancement]: Support the bilingual llm request

### ISSUE THREAD

**Issue by deerleo** [zilliztech/GPTCache#374]
### What would you like to be added?

When I asked multiple questions, it always return same answers only because they mention same keywords.

Like:
I asked "what is coffee(咖啡是什么)", 
it returns. " Coffee is a drink make of coffee beans " ... bla bla. 
Correct answer.
But When I asked it "How to make Americano coffee(美式咖啡怎么制作的)", it answered me with same answer like above question.

Expected a better NLP.

### Why is this needed?

Because it's totally different question.

**Comment by SimFG** [comment]
If you want to support bilingual cache, you need to use an embedding model that supports bilingual.

**Comment by SimFG** [comment]
The next version, we will support the bilingual embedding model, which is `uform`, link: https://github.com/unum-cloud/uform

**Comment by SimFG** [comment]
the latest version has support, reference: https://gptcache.readthedocs.io/en/latest/references/embedding.html#module-gptcache.embedding.uform
