### ISSUE TITLE
[Bug]: Cache not writing when prompt is greater than 1000 characters for SQL Scalar Cache

### ISSUE THREAD

**Issue by quillan86** [zilliztech/GPTCache#378]
### Current Behavior

I have a large prompt that I want to cache (it's part of a prompt template in langchain where the query itself is small but the complete template is large) and it is not saving to cache because the prompt is > 1000 characters.

The expected output result itself is small (e.g. ~256 characters) but it's large due to it being explicit instructions. The bug I get is this:

```
2023-05-22 11:28:08,013 - 140704405832512 - adapter.py-adapter:162 - WARNING: failed to save the data to cache, error: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]String or binary data would be truncated in table 'gambrinus-cachestore.dbo.gptcache_question', column 'question'. Truncated value: '...'. (2628) (SQLExecDirectW)")
[SQL: INSERT INTO gptcache_question (question, create_on, last_access, embedding_data, deleted) OUTPUT inserted.id VALUES (?, ?, ?, ?, ?)]
[parameters: ('... (1424 characters truncated) ...', datetime.datetime(2023, 5, 22, 11, 28, 7, 965579), datetime.datetime(2023, 5, 22, 11, 28, 7, 965586), bytearray(b'e\xe4 \xbd\xb1CA=\xed\x96\x00<\x1b\xa9\xbd\xbd\xd4\x8c7\xbd\xde\x93]\xbd4\x0c\xd2\xbb\xbfo$\xbd\x01\x89\x82=\xb1\xff\xe5<\xb7\xd25\xbd\xf0 ... (8408 characters truncated) ... xb8 \'\xbdM\xab\xb6\xbc\xd3\xc7\x84=\x93a\x15=\xe9\x03A\xbd\xde\xe2\x18\xbd)0\x1c\xbb\x86\x95\x08<Vl\x19=T\x9c\x95\xbdX\x13j\xbdEg\x11\xbdk\xafi\xbd'), 0)]
(Background on this error at: https://sqlalche.me/e/20/f405)

```

I see that the ultimate issue is that the question in the [question table is set to varchar(1000)](https://github.com/zilliztech/GPTCache/blob/main/gptcache/manager/scalar_data/sql_storage.py) which would be too small for this prompt.  The test prompt I am using has 1706 characters. This is with SQL Server, but the bug doesn't seem to be specific to SQL Server but SQL in general as a scalar cache.

### Expected Behavior

Allow the question column in the question table to be larger, either as a flexible variable or large enough for most LLMs (larger than 1000 characters anyway).

### Steps To Reproduce

```markdown
1. Create a SQL Server Scalar Cache.
2. Input a total prompt with > 1000 characters as input.
3. Attempt to run the cache.
```

### Environment

```markdown
here's the data manager. max_size and clean_size doesn't seem to do anything.


cache_base = CacheBase('sqlserver', sql_url=SQL_URL, table_name="gptcache")
vector_base = VectorBase('milvus', host=vector_database['host'], port=vector_database['port'],
                         user=vector_database['user'], password=vector_database['password'], secure=vector_database['secure'],
                         collection_name=vector_database['collection_name'], search_params=vector_database['search_params'], local_mode=vector_database['local_mode'],
                         dimension=onnx.dimension)

data_manager = get_data_manager(cache_base, vector_base, max_size=5000, clean_size=200)
```
```


### Anything else?

_No response_

**Comment by SimFG** [comment]
@quillan86 thanks a lot your feedback. A temporary solution is that you can manually modify the table structure in sqlserver to expand the length of the string. Regarding the big prompt, I am trying to find a solution recently, and of course I am looking forward to some of your ideas.

**Comment by quillan86** [comment]
Yes, that's what I did for now, but I'd ideally want this in production under docker so would need a way to handle that non-locally (e.g in a package).

Some ideas would be to perhaps use Text instead of String for the question and response, or for varchar make it some sort of variable a human can set with the data manager.

**Comment by quillan86** [comment]
See that this is in the latest version now - awesome work!

**Comment by SimFG** [comment]
@quillan86 yes, it will solve your problem. there are two ways:
1. config the data size for the table
2. use the `last_content_without_template` pre-process function
😆😆😆

**Comment by SimFG** [comment]
hi, @quillan86 the latest version can solve the problem, details: https://github.com/zilliztech/GPTCache/blob/main/docs/release_note.md
