### ISSUE TITLE
[DOCS]: Dose Llamacpp have usage example?

### ISSUE THREAD

**Issue by Zjq9409** [zilliztech/GPTCache#393]

**Comment by SimFG** [comment]
reference: https://github.com/zilliztech/GPTCache/tree/main/examples/integrate/llama_cpp

**Comment by Zjq9409** [comment]
what the difference between
`` ` if settings.cache:
        cache = llama_cpp.LlamaCache(capacity_bytes=settings.cache_size)
        llama.set_cache(cache)
```
and GPTCache

**Comment by Zjq9409** [comment]
in `gptcache/adapter/llama_cpp.py` , currently, only llama_cpp Q&A scenarios are supported? I see the parameter `prompt` only support strings?
```
def __call__(
            self,
            prompt: str,
            **kwargs
    ):
```

**Comment by Zjq9409** [comment]
```
cache.init(
    pre_embedding_func=all_content,
    embedding_func=huggingface.to_embeddings,
    data_manager=data_manager,
    similarity_evaluation=SearchDistanceEvaluation(),
    post_process_messages_func=temperature_softmax,
)
```
for multi round conversations, is it just to splits the messages from multiple rounds of conversations and store them as monologues?
 对话信息怎么记录呢？比如：
[
    {
        "role": "user",
        "content": "2+3等于几" 
    },
    {
        "role": "user",
        "content": "结果+4等于几" 
    }
]
