### ISSUE TITLE
How to set similarity_threshold

### ISSUE THREAD

**Issue by zhuwenxing** [zilliztech/GPTCache#4]
Does this variable have a range? I think it would be [0,1], but in the following code, it was a very large number.

https://github.com/zilliztech/gptcache/blob/d730fde6326f56df360a2f276d321d5f12c4aecd/example/sqlite_faiss_towhee/sqlite_faiss_towhee.py#L24

**Comment by SimFG** [comment]
This is related to the similarity evaluation algorithm. I think this range should be uncontrollable, because the connected similarity evaluation algorithm may generate large values, and there may also be negative numbers.

**Comment by xiaofan-luan** [comment]
I think we should setup a rule.
By default everything should be changed to something between 0-1

**Comment by xiaofan-luan** [comment]
if we use cosine similarity, by default it should be 0-1
