### ISSUE TITLE
[Enhancement]: Ability to track token usage

### ISSUE THREAD

**Issue by eliorc** [zilliztech/GPTCache#402]
### What would you like to be added?

In LangChain, it is possible to get the information regarding token usage from OpenAI.
It looks like this

```python
from langchain.llms import OpenAI
from langchain.callbacks import get_openai_callback

llm = OpenAI(model_name="text-davinci-002", n=2, best_of=2)

with get_openai_callback() as cb:
    result = llm("Tell me a joke")
    print(cb)
```

> Tokens Used: 42
> 	Prompt Tokens: 4
> 	Completion Tokens: 38
> Successful Requests: 1
> Total Cost (USD): $0.00084

To mimic this with GPTCache, I did the following

```python
from gptcache import cache
from gptcache.adapter.langchain_models import LangChainChat
from langchain.callbacks import get_openai_callback
from langchain.chat_models import ChatOpenAI
from langchain.schema import HumanMessage, SystemMessage


def get_msg_func(data, **_):
    return data.get("messages")[-1].content


cache.init(pre_embedding_func=get_msg_func)
cache.set_openai_key()

chat = ChatOpenAI()
cached_llm = LangChainChat(chat=chat)

messages = [SystemMessage(content="You should answer only one line answers"),
            HumanMessage(content="Tell me a story about yourself")]

with get_openai_callback() as cb:
    result = cached_llm(messages, cache_skip=True)
```

> Tokens Used: 0
> 	Prompt Tokens: 0
> 	Completion Tokens: 0
> Successful Requests: 0
> Total Cost (USD): $0.0

Using any model, including `gpt-4` results in zero cost, meaning the callback is not working.

Since usage is important, we need to find a way to make the token usage accessible to users of GPTCache

### Why is this needed?

To track usage effectively

**Comment by SimFG** [comment]
@eliorc Thank you for expressing your interest in GPTCache. Your proposal is excellent and certainly worth noting.

**Comment by SimFG** [comment]
The problem will be solved in the next version.

**Comment by eliorc** [comment]
@SimFG awesome
