### ISSUE TITLE
[Feature]:How to use own llm model service to replace openai api

### ISSUE THREAD

**Issue by Aries-ckt** [zilliztech/GPTCache#407]
### Is your feature request related to a problem? Please describe.

hi, now i have my own llm model service, i want to cache my own model service response, and i found gptcache must set set_openai_key, so how do i cache my own llm model service in gptcache?

**Comment by SimFG** [comment]
@Aries-ckt I understand that you proxy the openai server?

**Comment by Aries-ckt** [comment]
> @Aries-ckt I understand that you proxy the openai server?

yeah, i can proxy the openapi server, i notice that i can just set open_api_key, but i can not set url,like this:MODEL_SERVER=http://127.0.0.1:8000,how to change the open api url to my own server url?

**Comment by SimFG** [comment]
![image](https://github.com/zilliztech/GPTCache/assets/21985684/7749e5b0-8650-4517-843b-cc17bc3b4afe)
you can try to set the `OPENAI_API_BASE` environment param, which is provided by the openai sdk

**Comment by Aries-ckt** [comment]
> ![image](https://user-images.githubusercontent.com/21985684/242912801-7749e5b0-8650-4517-843b-cc17bc3b4afe.png) you can try to set the `OPENAI_API_BASE` environment param, which is provided by the openai sdk

thanks, i'll try. by the way, gptcache only support openai api service or proxy openai service?can it support my own model service, like Vicuna model service or chatglm model service?

**Comment by SimFG** [comment]
yes, it can. You can learn about the GPTCache api

**Comment by SimFG** [comment]
reference: https://gptcache.readthedocs.io/en/latest/references/adapter.html#module-gptcache.adapter.api

**Comment by Aries-ckt** [comment]
> https://gptcache.readthedocs.io/en/latest/references/adapter.html#module-gptcache.adapter.api

thanks.
