### ISSUE TITLE
how to cache multi round conversation

### ISSUE THREAD

**Issue by Zjq9409** [zilliztech/GPTCache#411]
### Documentation Link

```
"messages": [
        {
            "role": "system",
            "content": "You are a helpful assistant."
        },
        {
            "role": "user",
            "content": "What is the capital of France?"
        }
    ],

```

how to cache multi round conversation?

**Comment by SimFG** [comment]
For multiple rounds of conversations, you can try to use the simple `all_content` preprocessing function, or use context preprocessing (summary or selection), or customize it according to your needs

**Comment by Zjq9409** [comment]
Does the put method on the client side support openapi?

**Comment by SimFG** [comment]
I don't quite understand what you mean. Does the `client` refer to the GPTCache? If so, `put` actually receives two strings, which are key and value, and the key is used for similar matching. Then use the `get` method to receive the key, and then perform similar matching. If it meets the threshold, it will return the value corresponding to the previous put.

In this case, you only need to convert the openai request into string, and call the get method before the request. If the value is not obtained, then request openai, and use put to store the data in the cache after obtaining the result.
