### ISSUE TITLE
[Enhancement]: v0.1.30 expose exceptions similar to OpenAI exceptions for better error handling

### ISSUE THREAD

**Issue by ubhisat** [zilliztech/GPTCache#416]
### What would you like to be added?

Currently base class exception from openai is caught and wrapped in `CacheError`
https://github.com/zilliztech/GPTCache/blob/e609246b56158c76f5cac7f3e488335bc0093323/gptcache/adapter/openai.py#LL56C5-L61C52

```python
@classmethod
    def _llm_handler(cls, *llm_args, **llm_kwargs):
        try:
            return super().create(*llm_args, **llm_kwargs) if cls.llm is None else cls.llm(*llm_args, **llm_kwargs)
        except openai.error.OpenAIError as e:
            raise CacheError("openai error") from e
```
This makes the client code a bit harder to distinguish between different errors for cases when different action needs to be taken when we hit a rate limit error or any other error.

**Proposal**

Add exception classes similar to RateLimitError, APIConnectionError, InvalidRequestError	[etc](https://platform.openai.com/docs/guides/error-codes/python-library-error-types). 

### Why is this needed?

This makes the client code a bit harder to distinguish between different errors for cases when different action needs to be taken when we hit a rate limit error, authentication error, connection error or any other error.

**Comment by SimFG** [comment]
@ubhisat Thank you very much for your feedback. It truly deserves attention. And i will improve it in the next version

**Comment by SimFG** [comment]
The bug has been fixed. #421
