### ISSUE TITLE
[Bug]: 使用MYSQL所为CacheBase生成的这几个表,gptcache_question..都不见有记录呢？

### ISSUE THREAD

**Issue by jiangbossB** [zilliztech/GPTCache#433]
### Current Behavior

生成的表无记录，设置cache未成功

### Steps To Reproduce

```markdown
encoder = tokenizer
    cache_base = CacheBase('mysql')
    # vector_base = VectorBase('milvus', host='localhost', port='19530', dimension=768, collection_name='chatbot')
    vector_base = VectorBase('faiss', dimension=768)
    data_manager = get_data_manager(cache_base, vector_base)
    def get_question(data, **kwargs):
        return question

    cache.init(pre_embedding_func=get_question,
               embedding_func=encoder.encode, data_manager=data_manager,
               similarity_evaluation=SearchDistanceEvaluation())

    llm = LangChainLLMs(llm=LLM())
```

### Environment

```markdown
torch 2.0.1
cuda：true
python：3.9
```

**Comment by SimFG** [comment]
hello, can you show the complete test demo code?

According to the current code, it seems impossible to run, mainly because of `pre_embedding_func`, `embedding_func` and `LLM`

**Comment by jiangbossB** [comment]
> hello, can you show the complete test demo code?
> 
> According to the current code, it seems impossible to run, mainly because of `pre_embedding_func`, `embedding_func` and `LLM`

Thank you very much for your reply.
My LLM class inherits the LLM of langchain(It doesn't seem to work either，Directly pass a loaded object：LangChainLLMs(llm=AutoModel.from_pretrained(path)), 
and then
I changed `embedding_func` to the same as the official document: embedding_func=onnx.to_embeddings,After changing this, it still doesn't work
The way to invoke a custom LLM is：response = llm._call()，I don't know how else to do it,Several requests with the same problem are still not recorded in the table, and the request speed has not improved.

**Comment by SimFG** [comment]
Maybe you give me a working code, I will be able to solve your problem faster, because I still don't understand your needs

**Comment by jiangbossB** [comment]
Perhaps, as the answer above, init is not used correctly
