### ISSUE TITLE
[DOCS]: Rate limit documentation in API

### ISSUE THREAD

**Issue by turian** [zilliztech/GPTCache#437]
### Describe the problem

The README says:

"LLM services frequently enforce [rate limits](https://platform.openai.com/docs/guides/rate-limits), which are constraints that APIs place on the number of times a user or client can access the server within a given timeframe. Hitting a rate limit means that additional requests will be blocked until a certain period has elapsed, leading to a service outage. With GPTCache, you can easily scale to accommodate an increasing volume of of queries, ensuring consistent performance as your application's user base expands."

However, I don't find in the API docs how rate limits are specified or enforced. Different users have different rate limits on, say, OpenAI.

What happens if I ask for 3M openai embeddings? I can't even figure that out from the main docs or API docs.

### Describe the improvement

Rate limiting should be clearly documented and configurable.

### Anything else?

https://github.com/openai/openai-cookbook/blob/main/examples/How_to_handle_rate_limits.ipynb

Note that rate limits are different for each user, and also for each OpenAI API.

**Comment by SimFG** [comment]
In fact, GPTCache does not impose any limits on the LLM request rate, but it is still able to alleviate this issue. This is because GPTCache can provide quick access to previously cached data, reducing the number of LLM requests needed. As a result, users can make more requests within a given time frame.
