### ISSUE TITLE
[Enhancement]: Postgres, ChromaDB, etc. in Dockerfile

### ISSUE THREAD

**Issue by turian** [zilliztech/GPTCache#438]
### What would you like to be added?

It would be nice to have a "maximal" Dockerfile that sets up all the dependencies, such as Postgres, Chroma, etc.

### Why is this needed?

Most of the friction in writing a caching layer like this is running the external DBs.

I have a hand-rolled version of GPTCache that uses sqlite and faiss, purely because these are so easy to install. I would love to adopt GPTCache if it gave me smooth one-liner access to a Postgres instance, Chroma instance, etc.

**Comment by SimFG** [comment]
The necessary dependencies will be automatically downloaded and installed prior to use, including within Docker.
