### ISSUE TITLE
[Enhancement / Documentation request]: Document or add support for getting a list of most requested terms from the cache,  reuse cache as a local "answer" DB

### ISSUE THREAD

**Issue by sivang** [zilliztech/GPTCache#441]
### What would you like to be added?

This proposes to have:
1. A way to get a list of the K most frequent "answers" from the cache.
2. A way to copy caches as response DBs around for deploying and reusing already learned caches (effectively used as mini response models)

### Why is this needed?

1. for local optimizations based on query frequency.
2. saving costs deploying a cache in a new project and continue adding to it in new deployment.

### Anything else?

I'm happy to work on this features / documentation bit, but I gather I'd need some contribution guidance :)

**Comment by SimFG** [comment]
@sivang Thanks your issues. 
Rough expectations are as follows:
1. Hope to `import` and `export` the data in the cache
2. Support obtaining the most frequently accessed data list in the cache, such as the 10 most frequently used cache data in the cache

Is there any deviation from the above description

**Comment by SimFG** [comment]
@sivang 
1. Regarding data migration, you can use relevant db tools for data migration
2. I have added a report table in the v0.1.35 version, and you can use it to analyze the cache data.
