### ISSUE TITLE
[Feature]: Query the frequency of hits for a cached search

### ISSUE THREAD

**Issue by Adam-Gibbs** [zilliztech/GPTCache#455]
### Is your feature request related to a problem? Please describe.

I would like to track how often searches for specific terms happen to be asked for

### Describe the solution you'd like.

Simply tracking them by iterating a value in the scalar store tied to the gptcache_question table, perhaps a column for `hits`.
I can then implement a custom data view that grabs the questions and their hit counts.

**Comment by SimFG** [comment]
Thank you for your suggestion. I am currently planning to implement it in the next version.

**Comment by SimFG** [comment]
@Adam-Gibbs I have added a `report` table, and you can use it to analyze the cache data.
