### ISSUE TITLE
[Feature]: Add Redis as a CacheStorage

### ISSUE THREAD

**Issue by pravingadakh** [zilliztech/GPTCache#458]
### Is your feature request related to a problem? Please describe.

Redis as Vector Store is already available, it will be good if it can be added as Cache Storage as well.

**Comment by SimFG** [comment]
Thank you for your attention. Redis is expected to be supported as a caching store next week. We also warmly welcome any contributions.

**Comment by a9raag** [comment]
Hi, @SimFG anyone already working on this? 
I don't mind contributing to this.

**Comment by SimFG** [comment]
@a9raag we welcome your contribution. And I have not yet commenced the development of this particular feature.

**Comment by SimFG** [comment]
Thank you very much for @a9raag's contribution. Currently, the `dev` branch already supports redis as a cache store. If you want a quick experience, you can try to install it through source code.

**Comment by dmitrypol** [comment]
does this require RediSearch module or can we use regular Redis?

**Comment by SimFG** [comment]
@dmitrypol yes, this requires.
reference: https://github.com/redis/redis-om-python#-so-how-do-you-get-redisearch-and-redisjson
![image](https://github.com/zilliztech/GPTCache/assets/21985684/77f98b89-c142-4144-bd47-12862a17380a)

**Comment by akshaysaini11** [comment]
Hi Team,
i have implement the redis with GPTcache. but code use below :

from gptcache.manager import manager_factory
data_manager = manager_factory("redis,faiss", data_dir="./workspace",
            scalar_params={
                    "redis_host":"localhost",
                    "redis_port":6379,
                    "global_key_prefix":"gptcache",
                },
                vector_params={"dimension": 128},
            )
this code run but show error :
    cmd_name = str_if_bytes(command[0])
TypeError: 'NoneType' object is not subscriptable

please provided solution and guidance.
kindly review.
Thanks,

**Comment by a9raag** [comment]
@akshaysaini11 
Can you check if you have redis json and search modules loaded for your redis? 
https://redis.io/resources/modules/
Or you can install redis-stack-server which comes pre-loaded with these modules.

**Comment by akshaysaini11** [comment]
> @akshaysaini11 Can you check if you have redis json and search modules loaded for your redis? https://redis.io/resources/modules/ Or you can install redis-stack-server which comes pre-loaded with these modules.
Hi @a9raag , 
redis with gptcache use windows and linux.
i am working for window but this suggestion for working in Linux, ubuntu.
please provide suggestion for window.
Thanks,
