### ISSUE TITLE
[Feature]:可以缓存embeding吗

### ISSUE THREAD

**Issue by yuanjie-ai** [zilliztech/GPTCache#469]
### Is your feature request related to a problem? Please describe.

可以缓存embeding吗

### Describe the solution you'd like.

可以缓存embeding吗

### Describe an alternate solution.

可以缓存embeding吗

### Anything else? (Additional Context)

可以缓存embeding吗

**Comment by SimFG** [comment]
No, it is not practical to cache embeddings in a similar way as complete matching caching is required. Instead, you can convert the embeddings into bytes and store them in traditional databases such as SQLite, MySQL, and others.
