### ISSUE TITLE
[DOCS]:  Any reference or guide on using MongoDB as for the cache 

### ISSUE THREAD

**Issue by OnlinePage** [zilliztech/GPTCache#476]
### Describe the improvement

Hi one of  the recent most version indicates that it supports MongoDB for caching, However i could not find any refrence to it in the documentation.
I am planning to use langchain with GPTCache with MongoDB.
Can we get some reference or a guide on this?

**Comment by SimFG** [comment]
Hi, @OnlinePage 
reference docs: 
1. [how to better configure your cache](https://gptcache.readthedocs.io/en/latest/configure_it.html#data-manager)
2. [mongo api reference](https://gptcache.readthedocs.io/en/latest/references/manager.html#module-gptcache.manager.scalar_data.mongo)

In general, you can use mongo as a cache store in this way, and the scalar_params parameter is the relevant parameter of the cache store, showing the default value of mongo

```
from gptcache.manager import manager_factory

data_manager = manager_factory("mongo,faiss", data_dir="./workspace", scalar_params={"mongo_host": "localhost", "mongo_port": 27017, dbname="gptcache", username="", password=""}, vector_params={"dimension": 128})
```

**Comment by akshaysaini11** [comment]
> Hi, @OnlinePage reference docs:
> 
> 1. [how to better configure your cache](https://gptcache.readthedocs.io/en/latest/configure_it.html#data-manager)
> 2. [recommended by newcomers](https://gptcache.readthedocs.io/en/latest/configure_it.html#recommended-by-newcomers)
> 3. [mongo api reference](https://gptcache.readthedocs.io/en/latest/references/manager.html#module-gptcache.manager.scalar_data.mongo)
> 
> In general, you can use mongo as a cache store in this way, and the scalar_params parameter is the relevant parameter of the cache store, showing the default value of mongo
> 
> ```
> from gptcache.manager import manager_factory
> 
> data_manager = manager_factory("mongo,faiss", data_dir="./workspace", scalar_params={"mongo_host": "localhost", "mongo_port": 27017, dbname="gptcache", username="", password=""}, vector_params={"dimension": 128})
> ```

this code use but show error: 
NotFoundError: Unsupported $cache store: mongo

my use code :
from gptcache.manager import manager_factory

data_manager = manager_factory("mongo,faiss", data_dir="./workspace", scalar_params={"mongo_host": "localhost", "mongo_port": 27017, "dbname":"gptcache", "username":"", "password":""}, vector_params={"dimension": 128})

**Comment by SimFG** [comment]
@akshaysaini11 What version of GPTCache are you using?

**Comment by akshaysaini11** [comment]
gptcache == 0.1.37

this version use

**Comment by akshaysaini11** [comment]
> @akshaysaini11 What version of GPTCache are you using?

gptcache == 0.1.37

this version use

**Comment by SimFG** [comment]
@akshaysaini11 there is testing output in my conputer.
![image](https://github.com/zilliztech/GPTCache/assets/21985684/ff7d1829-985a-4697-be74-bf1667c4da1c)
I guess your computer has some python environment. you can try to check the GPTCache version by using `python -m pip show gptcache`

**Comment by akshaysaini11** [comment]
> i try to this suggestion but same issue.
![12345](https://github.com/zilliztech/GPTCache/assets/140800660/0c68a620-8b9b-4cac-ab7b-1c0470c8ca9d)

**Comment by akshaysaini11** [comment]
> @akshaysaini11 there is testing output in my conputer. ![image](https://user-images.githubusercontent.com/21985684/256797176-ff7d1829-985a-4697-be74-bf1667c4da1c.png) I guess your computer has some python environment. you can try to check the GPTCache version by using `python -m pip show gptcache` ![image](https://user-images.githubusercontent.com/21985684/256797620-a91f2fdf-e1cf-41a5-b84a-3d6402c5bf06.png)

Hi Brother,
sorry, i have check for vs code.it is working for your code in vs code.
Thanks,
