### ISSUE TITLE
[Feature]: support for distributed cache

### ISSUE THREAD

**Issue by a9raag** [zilliztech/GPTCache#496]
### Is your feature request related to a problem? Please describe.

As far as I know, in the current implementation, the caching eviction is done in memory using `cachetools` library. 
Which makes caching limited to the local system. 

Support for the distributed cache using Redis or Memcached will allow gptcache to scale horizontally. 
the 

### Describe the solution you'd like.

The initial idea for this would be: 
1. Implement a distributed cache eviction analogous to the current [MemoryCacheEviction ](https://github.com/zilliztech/GPTCache/blob/10dcfae0e4ea848391ab3710537ffe0017512769/gptcache/manager/eviction/memory_cache.py). 
2. Add support for Redis or Memcached or both to maintain and evict the cache. 
3. Add functionality to load the distributed cache based on the provided configuration

**Comment by a9raag** [comment]
If you guys this seems valid and would work. 
I can start working on this.

**Comment by SimFG** [comment]
@a9raag yes, you‘re right!  Looking forward to your pr
