### ISSUE TITLE
[Feature]: Want a custom schema support for weaviate classes

### ISSUE THREAD

**Issue by pranaychandekar** [zilliztech/GPTCache#497]
### Is your feature request related to a problem? Please describe.

If we use weaviate as the vector data store, then it creates a class with default schema. We cannot create the weaviate cache class with custom schema.

### Describe the solution you'd like.

I want to create the weaviate cache class with custom schema

**Comment by pranaychandekar** [comment]
@SimFG I have a solution in mind for this one. Please assign this to me

**Comment by SimFG** [comment]
@pranaychandekar done! thanks for your contribution
