### ISSUE TITLE
[Enhancement]:support Azure Open AI 

### ISSUE THREAD

**Issue by Zhuyaguang782126** [zilliztech/GPTCache#506]
### What would you like to be added?

支持 Azure Open AI  

### Why is this needed?

国内访问 open AI 不太方便，目前 Azure Open AI 没有此类限制

**Comment by SimFG** [comment]
It can be used only by modifying the variables in the `openai` package, and I understand that no additional support is required. Reference: https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/switching-endpoints

**Comment by Zhuyaguang782126** [comment]
yes , i add some code ,it works

![image](https://github.com/zilliztech/GPTCache/assets/140598706/cbb009b1-1460-42c0-ae9f-1f42ee89caed)
