### ISSUE TITLE
[Feature]: Allow me to set Cache key as model + prompt

### ISSUE THREAD

**Issue by ishaan-jaff** [zilliztech/GPTCache#527]
### Is your feature request related to a problem? Please describe.

I need to cache based on model + prompt as the key. Looks like gpt cache is only caching based on the prompt 

### Describe the solution you'd like.

Expose the ability to define the key for caching

**Comment by SimFG** [comment]
@ishaan-jaff you can achieve this by customizing the `pre_process_func`, and you can refer to `last_content_without_prompt`

**Comment by ishaan-jaff** [comment]
I don't see `pre_process_func` defined in the code base 

Is `last_content_without_prompt` called as the pre_proccess_func for gpt-3.5-turbo ?

**Comment by ishaan-jaff** [comment]
Done: added some docs on doing this for our users at LiteLLM: https://docs.litellm.ai/docs/caching/gpt_cache#advanced-usage---set-custom-cache-keys

**Comment by ishaan-jaff** [comment]
thanks @SimFG
