### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Bala534** [zilliztech/GPTCache#529]
### Current Behavior

Hi I am Building the apis where the input prompt will send to the chatgpt and gets the response.
I was implemented using gptcache in fastapi python.
But the api responses was getting same and sometimes getting the older api responses eventhough the input to the api and the input prompt to the chatgpt was sending correctly.

**Comment by SimFG** [comment]
please give more information about your problem, like: your demo code. and you should write more reasonable issue title
