### ISSUE TITLE
[DOCS]: Overall update: Cache Storage, Vector Storage

### ISSUE THREAD

**Issue by a9raag** [zilliztech/GPTCache#536]
### Documentation Link

I think the documentation needs to be updated for new features that were integrated

- Cache Storage 
Mongo, Redis, and more Cache storage implementations are now supported. 

- Vector Store 
I believe qdrant and weaviate support is now there 

- Cache Manager 
 Support for distributed cache 

### Describe the problem

Documentation is missing

**Comment by a9raag** [comment]
If the maintainers approve, I can take this up and add the documentation mentioned above.

**Comment by SimFG** [comment]
@a9raag Sure, do it
