### ISSUE TITLE
[Bug]: RuntimeError: The size of tensor a (2467) must match the size of tensor b (512) at non-singleton dimension 1

### ISSUE THREAD

**Issue by sdd031215** [zilliztech/GPTCache#584]
### Current Behavior

cache_embeddings = Huggingface("model/bge-large-zh-v1.5")
def get_content_func(data, **_):
            return data.get("prompt").split("Question")[-1]

def init_gptcache_map(cache_obj: Cache):
    cache_base = CacheBase('sqlite')
    vector_base = VectorBase('milvus', host='xx', port='19530', dimension=1024, collection_name='chatbot')
    data_manager = get_data_manager(cache_base, vector_base)
    cache_obj.init(
        pre_embedding_func=get_content_func,
        embedding_func=cache_embeddings.to_embeddings,
        data_manager=data_manager,
        similarity_evaluation=SearchDistanceEvaluation(),  
        )
langchain.llm_cache = GPTCache(init_gptcache_map)

### Expected Behavior

I need your help , thanks.  @SimFG @technicalpickles @jmahmood @shanghaikid @leio10 @cxie

**Comment by SimFG** [comment]
@sdd031215 The same code, has the embedding function been modified in the last running?

**Comment by sdd031215** [comment]
> @sdd031215 The same code, has the embedding function been modified in the last running?

no

**Comment by sdd031215** [comment]
cache_base = CacheBase('sqlite')
vector_base = VectorBase('milvus', host='xx', port='19530', dimension=1024, collection_name='chatbot')
data_manager = get_data_manager(cache_base, vector_base, max_size=100000)

init_similar_cache( pre_func=get_prompt, 
                cache_obj=cache,  
                embedding=cache_embeddings, 
                data_manager=data_manager,
                # evaluation=SearchDistanceEvaluation(max_distance=0.5, positive=True)
                )

**Comment by sdd031215** [comment]
> confirm

confirm

> I probably guessed the reason, it's because the dimensions are set wrong. You can confirm whether the model you are using is from 1024dim.

i confirm

**Comment by sdd031215** [comment]
> cache_base = CacheBase('sqlite') vector_base = VectorBase('milvus', host='xx', port='19530', dimension=1024, collection_name='chatbot') data_manager = get_data_manager(cache_base, vector_base, max_size=100000)
> 
> init_similar_cache( pre_func=get_prompt, cache_obj=cache, embedding=cache_embeddings, data_manager=data_manager, # evaluation=SearchDistanceEvaluation(max_distance=0.5, positive=True) )
> 
> **This method can be executed, but it is not written in sqlite and milvus. Please help me figure out why**

Is there anything missing in this method?

**Comment by SimFG** [comment]
@sdd031215 no, Because it is an initialization step, no data will be written
