### ISSUE TITLE
[Feature]: GPTCache openAI should make the cached result more similar to openAI response

### ISSUE THREAD

**Issue by xiaofan-luan** [zilliztech/GPTCache#61]
### Is your feature request related to a problem? Please describe.

ChatGPT returned
{
  "choices": [
    {
      "finish_reason": "stop",
      "index": 0,
      "message": {
        "content": "The Valley of Kings is located in the west bank of the Nile river in Luxor, Egypt.",
        "role": "assistant"
      }
    }
  ],
  "created": 1680670004,
  "id": "chatcmpl-71pKeRARTWzSiQE5uu6NzKkZYUTLE",
  "model": "gpt-3.5-turbo-0301",
  "object": "chat.completion",
  "usage": {
    "completion_tokens": 20,
    "prompt_tokens": 229,
    "total_tokens": 249
  }
}

GPT cache returned
{'gptcache': True, 'choices': [{'message': {'role': 'assistant', 'content': 'The Valley of Kings is located in the west bank of the Nile river in Luxor, Egypt.'}, 'finish_reason': 'stop', 'index': 0}]}

currently,  the gpt cache returned is similar in choices but lack other field such as usage and created time

**Comment by zhuwenxing** [comment]
I think the `usage` should be changed to  `usage_saved` in the return of gptcache to reflect the value of gptcache.

**Comment by xiaofan-luan** [comment]
we can return 0 if we want~

**Comment by SimFG** [comment]
> I think the `usage` should be changed to `usage_saved` in the return of gptcache to reflect the value of gptcache.

If someone else raises this part, we are working on it
